# Generated by Django 5.2.16 on 2026-09-16 05:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicProgram',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('program_name', models.CharField(max_length=100)),
                ('program_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('ONLINE', 'Online')], max_length=50)),
                ('duration', models.PositiveIntegerField(help_text='Duration in years')),
                ('total_credits', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('is_full_crud', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['program_name'],
            },
        ),
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('term_id', models.AutoField(primary_key=True, serialize=False)),
                ('academic_year', models.CharField(help_text='Example: 2026-2027', max_length=9)),
                ('term_name', models.CharField(choices=[('FALL', 'Fall'), ('SPRING', 'Spring'), ('SUMMER', 'Summer'), ('WINTER', 'Winter')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('registration_start', models.DateField(blank=True, null=True)),
                ('registration_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_full_crud', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['academic_year', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='AreaOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_name', models.CharField(max_length=100, unique=True)),
                ('is_full_crud', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
            ],
            options={
                'ordering': ['interest_name'],
            },
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('degree_id', models.AutoField(primary_key=True, serialize=False)),
                ('degree_name', models.CharField(max_length=255, unique=True)),
                ('degree_code', models.CharField(max_length=50, unique=True)),
                ('level', models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('PHD', 'Doctorate')], max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('is_full_crud', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['level', 'degree_name'],
            },
        ),
        migrations.CreateModel(
            name='ProgramConcentration',
            fields=[
                ('concentration_id', models.AutoField(primary_key=True, serialize=False)),
                ('concentration_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_full_crud', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramCourse',
            fields=[
                ('program_course_id', models.AutoField(primary_key=True, serialize=False)),
                ('study_year', models.PositiveSmallIntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4'), (5, 'Year 5')])),
                ('term', models.CharField(choices=[('FALL', 'Fall'), ('SPRING', 'Spring'), ('SUMMER', 'Summer'), ('WINTER', 'Winter')], max_length=20)),
                ('is_elective', models.BooleanField(default=False, help_text='Check if this course is an elective.')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_full_crud', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'program_course',
                'ordering': ['program', 'study_year', 'term', 'course'],
            },
        ),
        migrations.CreateModel(
            name='ProgramSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveIntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')])),
                ('is_elective', models.BooleanField(default=False)),
                ('is_full_crud', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=255)),
                ('school_short_name', models.CharField(max_length=100)),
                ('school_code', models.CharField(max_length=30)),
                ('school_type', models.CharField(choices=[('ACADEMIC', 'Academic'), ('PROFESSIONAL', 'Professional'), ('GRADUATE', 'Graduate')], default='ACADEMIC', max_length=20)),
                ('official_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('building_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('established_year', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='schools/')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_full_crud', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['school_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentProgramEnrollment',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('admission_year', models.PositiveIntegerField()),
                ('current_semester', models.PositiveIntegerField(default=1)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('DROPPED', 'Dropped'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('is_full_crud', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_code', models.CharField(max_length=50, unique=True)),
                ('subject_name', models.CharField(max_length=255)),
                ('credits', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_full_crud', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('university_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('university_name', models.CharField(max_length=255)),
                ('university_short_name', models.CharField(max_length=100)),
                ('university_code', models.CharField(max_length=30, unique=True)),
                ('university_type', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=20)),
                ('ownership_type', models.CharField(choices=[('STATE', 'State Government'), ('CENTRAL', 'Central Government'), ('PRIVATE', 'Private')], default='STATE', max_length=20)),
                ('official_email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True, null=True)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('established_year', models.PositiveIntegerField()),
                ('accreditation', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='universities/')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_full_crud', models.BooleanField(default=False)),
            ],
        ),
    ]
