# Generated by Django 5.2.16 on 2026-09-16 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Colleges', '0001_initial'),
        ('bela_admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academicprogram',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='bela_admin.department'),
        ),
        migrations.AlterUniqueTogether(
            name='academicterm',
            unique_together={('academic_year', 'term_name')},
        ),
        migrations.AddField(
            model_name='academicprogram',
            name='areas_of_interest',
            field=models.ManyToManyField(blank=True, related_name='programs', to='Colleges.areaofinterest'),
        ),
        migrations.AddField(
            model_name='academicprogram',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='Colleges.degree'),
        ),
        migrations.AddField(
            model_name='programconcentration',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concentrations', to='Colleges.academicprogram'),
        ),
        migrations.AddField(
            model_name='programcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_courses', to='bela_admin.course'),
        ),
        migrations.AddField(
            model_name='programcourse',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_courses', to='Colleges.academicprogram'),
        ),
        migrations.AddField(
            model_name='programsubject',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_subjects', to='Colleges.academicprogram'),
        ),
        migrations.AddField(
            model_name='school',
            name='dean',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools_as_dean', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentprogramenrollment',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='Colleges.academicprogram'),
        ),
        migrations.AddField(
            model_name='programsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_programs', to='Colleges.subject'),
        ),
        migrations.AddField(
            model_name='school',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='Colleges.university'),
        ),
        migrations.AddConstraint(
            model_name='academicprogram',
            constraint=models.UniqueConstraint(fields=('department', 'degree', 'program_name'), name='unique_department_degree_program'),
        ),
        migrations.AddConstraint(
            model_name='programcourse',
            constraint=models.UniqueConstraint(fields=('program', 'study_year', 'term', 'course'), name='unique_program_curriculum'),
        ),
        migrations.AlterUniqueTogether(
            name='programsubject',
            unique_together={('program', 'subject')},
        ),
        migrations.AddConstraint(
            model_name='school',
            constraint=models.UniqueConstraint(fields=('university', 'school_name'), name='unique_school_name_per_university'),
        ),
        migrations.AddConstraint(
            model_name='school',
            constraint=models.UniqueConstraint(fields=('university', 'school_code'), name='unique_school_code_per_university'),
        ),
    ]
