# Generated by Django 5.2.16 on 2026-09-16 05:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
        ('Medical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_key', models.CharField(help_text='Unique slug indentifying this page in code.', max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('path_prefix', models.CharField(help_text='URL path prefix this page covers. Every request whose path starts with this prefix is checked against this PageAccess record by the middleware.', max_length=200, unique=True)),
                ('category', models.CharField(default='General', help_text="Groups this page under a section in the Page Access UI (e.g. 'User Management').", max_length=100)),
                ('icon', models.CharField(default='file', help_text='Lucide icon name shown next to this page in the Page Access UI.', max_length=50)),
                ('is_auto_discovered', models.BooleanField(default=False, help_text='True if this record was created by the page-sync scanner rather than manually.')),
                ('shared_with_user_roles', models.BooleanField(default=False, help_text="Only meaningful when category is 'Medical'. When True, this page moves to the Admin tab instead of the Medical tab (exclusive switch, not additive) — use this only for the pages that live under the Admin sidebar's 'Medical' dropdown (e.g. Departments, Staff, Patients Profile, Appointments, Healthcamp Management, Hospital Dashboard, Book Appointment, Athletes Profile). Medical-only operational pages (Shift Management, My Shifts, Staff Schedule, Assign Medical Staff) must stay False so they always stay on the Medical tab. NOT admin-editable in the Page Access UI — set `shared_with_user_roles` as a class attribute on the view (see discovery.py) and click 'Scan for new pages' to apply it.")),
                ('user_types', models.JSONField(blank=True, default=list, help_text="Which Admin.UserRole.user_type values (e.g. 'admin', 'staff', 'faculty', 'student') can see this page in the Roles & Permissions / Page Access UI. A page can belong to more than one tab (e.g. ['staff', 'faculty']). Empty list = shows under the Admin tab only until explicitly tagged. Not used when category is 'Medical' — Medical pages use `shared_with_user_roles` instead. NOT admin-editable here — set `user_types` as a class attribute on the view (see discovery.py) and click 'Scan for new pages' to apply it.")),
                ('breadcrumb', models.CharField(blank=True, help_text="Where this page sits, shown in the Page Access UI (e.g. 'Medical > Staff'). Developer-provided, NOT auto-generated and NOT admin-editable in the Page Access UI — set `page_path` as a class attribute on the view (PageAccessMixin) or a kwarg on `require_page_access` (see mixins.py / decorators.py), then click 'Scan for new pages' or re-run migrate to apply it. Left blank until the developer sets it — the UI falls back to 'Category > Display Name' meanwhile so nothing breaks.", max_length=255)),
                ('medical_roles', models.ManyToManyField(blank=True, related_name='page_accesses', to='Medical.medicalstaffrole')),
                ('roles', models.ManyToManyField(blank=True, help_text='UserRole groups allowed to see/open this page.', related_name='page_accesses', to='Admin.userrole')),
            ],
            options={
                'verbose_name': 'Page Access',
                'verbose_name_plural': 'Page Accesses',
                'db_table': 'permission_access_page_access',
                'ordering': ['category', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('codename', models.CharField(max_length=150, unique=True)),
                ('model_label', models.CharField(max_length=100)),
                ('app_label', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('display_label', models.CharField(blank=True, help_text="Optional override for how this permission is labelled in the Roles & Permissions UI. Can be a plain name ('Media Block') or a full breadcrumb using '>' as the separator (e.g. 'Medical > Staff > Assign Medical Staff') — the last segment is shown as the model name in the CRUD grid, and the full breadcrumb (plus the action) is shown in the C/R/U/D tooltip. Leave blank to auto-generate from the source model's verbose_name — most models never need to set this. Set as a `permission_label` class attribute on the source model (see signals.py), not here.", max_length=150)),
                ('is_full_crud', models.BooleanField(default=True, help_text="Mirrors the source model's is_full_crud flag. False means this model only ever gets a 'read' permission and is hidden from the CRUD matrix UI.")),
                ('shared_with_user_roles', models.BooleanField(default=False, help_text="Only meaningful when app_label is 'Medical'. When True, this model's CRUD permissions move to the Admin tab instead of the Medical tab (exclusive switch, not additive). Mirrors the source model's own `shared_with_user_roles` flag — set it as a field on the model (see signals.py), not here.")),
                ('user_types', models.JSONField(blank=True, default=list, help_text="Which Admin.UserRole.user_type values (e.g. 'admin', 'staff', 'faculty', 'student') can see and be granted this permission in the Roles & Permissions UI. A permission can belong to more than one tab (e.g. ['staff', 'admin']). Empty list = shows under the Admin tab only until explicitly tagged. Not used for app_label 'Medical' — Medical uses `shared_with_user_roles` instead. Set as a `user_types` class attribute on the source model (see signals.py), not here.")),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'permissions_access_permissions',
                'ordering': ['app_label', 'model_label', 'action'],
                'unique_together': {('model_label', 'action', 'app_label')},
            },
        ),
        migrations.CreateModel(
            name='PermissionAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('action', models.CharField(choices=[('permission_assigned', 'Permission Assigned'), ('permission_removed', 'Permission Removed'), ('page_access_changed', 'Page Access Changed'), ('unauthorized_attempt', 'Unauthorized Attempt'), ('administrator_setup', 'Administrator Setup')], max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('action_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('target_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_audit_logs', to='Admin.userrole')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rbac_audit_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'permission_access_audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
