# Generated by Django 5.2.16 on 2026-09-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_code', models.CharField(max_length=50, unique=True)),
                ('event_title', models.CharField(max_length=255)),
                ('event_subtitle', models.CharField(blank=True, max_length=255)),
                ('event_description', models.TextField()),
                ('organizer_type', models.CharField(choices=[('Department', 'Department'), ('Student Organization', 'Student Organization'), ('Administration', 'Administration')], max_length=50)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('event_mode', models.CharField(choices=[('Online', 'Online'), ('Hybrid', 'Hybrid'), ('Offline', 'Offline')], default='Offline', max_length=10)),
                ('event_status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Draft', max_length=20)),
                ('event_visibility', models.CharField(choices=[('Public', 'Public'), ('Campus Only', 'Campus Only'), ('Invitation Only', 'Invitation Only')], default='Campus Only', max_length=20)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('registration_required', models.BooleanField(default=False)),
                ('is_paid_event', models.BooleanField(default=False)),
                ('event_cost', models.TextField(blank=True)),
                ('event_website', models.URLField(blank=True)),
                ('has_accessibility_information', models.BooleanField(default=False)),
                ('accessibility_email', models.EmailField(blank=True, max_length=254)),
                ('accessibility_phone', models.CharField(blank=True, max_length=20)),
                ('max_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_full_crud', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EventBudget',
            fields=[
                ('budget_id', models.AutoField(primary_key=True, serialize=False)),
                ('allocated_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actual_expense', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_full_crud', models.BooleanField(default=False)),
                ('remaining_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_full_crud', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EventCertificate',
            fields=[
                ('certificate_id', models.AutoField(primary_key=True, serialize=False)),
                ('certificate_number', models.CharField(max_length=100, unique=True)),
                ('is_full_crud', models.BooleanField(default=False)),
                ('issue_date', models.DateField()),
                ('certificate_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='EventFeedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('is_full_crud', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventNotification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('Registration Confirmation', 'Registration Confirmation'), ('Reminder', 'Reminder'), ('Schedule Change', 'Schedule Change'), ('Cancellation Notice', 'Cancellation Notice'), ('Thank You Message', 'Thank You Message')], max_length=50)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_full_crud', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('registration_id', models.AutoField(primary_key=True, serialize=False)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('attendance_status', models.CharField(choices=[('Registered', 'Registered'), ('Present', 'Present'), ('Absent', 'Absent')], default='Registered', max_length=20)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('is_full_crud', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EventSession',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_title', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('room_number', models.CharField(max_length=100)),
                ('is_full_crud', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EventSpeaker',
            fields=[
                ('speaker_id', models.AutoField(primary_key=True, serialize=False)),
                ('speaker_name', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('biography', models.TextField(blank=True, null=True)),
                ('is_full_crud', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='EventSponsor',
            fields=[
                ('sponsor_id', models.AutoField(primary_key=True, serialize=False)),
                ('sponsor_name', models.CharField(max_length=255)),
                ('sponsorship_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_full_crud', models.BooleanField(default=False)),
                ('sponsorship_type', models.CharField(choices=[('Platinum', 'Platinum'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EventVenue',
            fields=[
                ('venue_id', models.AutoField(primary_key=True, serialize=False)),
                ('venue_name', models.CharField(max_length=255)),
                ('building_name', models.CharField(max_length=255)),
                ('room_number', models.CharField(max_length=50)),
                ('is_full_crud', models.BooleanField(default=False)),
                ('seating_capacity', models.PositiveIntegerField()),
                ('location_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
