# Generated by Django 5.2.16 on 2026-09-16 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Applicants', '0001_initial'),
        ('Colleges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicanttyperequirement',
            name='degree_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Colleges.degree'),
        ),
        migrations.AddField(
            model_name='application',
            name='admission_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='Applicants.admissioncycle'),
        ),
        migrations.AddField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='Applicants.applicant'),
        ),
        migrations.AddField(
            model_name='application',
            name='backup_program',
            field=models.ForeignKey(blank=True, help_text='Second-choice (backup) program', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='backup_applications', to='Colleges.academicprogram'),
        ),
        migrations.AddField(
            model_name='application',
            name='degree_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='Colleges.degree'),
        ),
    ]
