# Generated by Django 5.2.16 on 2026-09-16 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Applicants', '0002_initial'),
        ('Colleges', '0001_initial'),
        ('bela_admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='bela_admin.department'),
        ),
        migrations.AddField(
            model_name='application',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='Colleges.academicprogram'),
        ),
        migrations.AddField(
            model_name='application',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='Colleges.school'),
        ),
        migrations.AddField(
            model_name='application',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='Colleges.university'),
        ),
        migrations.AddField(
            model_name='applicationchecklistitem',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='Applicants.application'),
        ),
        migrations.AddField(
            model_name='applicationessay',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essays', to='Applicants.application'),
        ),
        migrations.AddField(
            model_name='applicationfee',
            name='degree_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_fees', to='Colleges.degree'),
        ),
        migrations.AddField(
            model_name='applicationfee',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_fees', to='Colleges.university'),
        ),
        migrations.AddField(
            model_name='applicationlog',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='Applicants.application'),
        ),
        migrations.AddField(
            model_name='applicationreviewassignment',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_assignment', to='Applicants.application'),
        ),
        migrations.AddField(
            model_name='applicationreviewassignment',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationreviewassignment',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationstatushistory',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='Applicants.application'),
        ),
        migrations.AddField(
            model_name='applicationtimeline',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='Applicants.application'),
        ),
        migrations.AddField(
            model_name='document',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Applicants.application'),
        ),
        migrations.AddField(
            model_name='documentrequirement',
            name='degree_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_requirements', to='Colleges.degree'),
        ),
        migrations.AddField(
            model_name='documentrequirement',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_requirements', to='Colleges.academicprogram'),
        ),
        migrations.AddField(
            model_name='documentrequirement',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_requirements', to='Colleges.university'),
        ),
        migrations.AddField(
            model_name='document',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to='Applicants.documentrequirement'),
        ),
        migrations.AddField(
            model_name='essayprompt',
            name='degree_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='essay_prompts', to='Colleges.degree'),
        ),
        migrations.AddField(
            model_name='essayprompt',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='essay_prompts', to='Colleges.academicprogram'),
        ),
        migrations.AddField(
            model_name='essayprompt',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='essay_prompts', to='Colleges.university'),
        ),
        migrations.AddField(
            model_name='applicationessay',
            name='essay_prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='Applicants.essayprompt'),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Applicants.application'),
        ),
        migrations.AddField(
            model_name='feewaiver',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_waivers', to='Applicants.application'),
        ),
        migrations.AddField(
            model_name='fieldchoice',
            name='depends_on_field',
            field=models.ForeignKey(blank=True, help_text='Parent choice for cascading selects', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_choices', to='Applicants.fieldchoice'),
        ),
        migrations.AddField(
            model_name='fieldcorrectionrequest',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_correction_requests', to='Applicants.application'),
        ),
        migrations.AddField(
            model_name='fieldcorrectionrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_correction_requests_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fieldreview',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_reviews', to='Applicants.application'),
        ),
        migrations.AddField(
            model_name='fieldreview',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_reviews', to='Applicants.applicationreviewassignment'),
        ),
        migrations.AddField(
            model_name='fieldreview',
            name='correction_request',
            field=models.ForeignKey(blank=True, help_text='The correction request this rejection was sent in (null until sent)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_reviews', to='Applicants.fieldcorrectionrequest'),
        ),
        migrations.AddField(
            model_name='fieldreview',
            name='field_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Applicants.fieldresponse'),
        ),
        migrations.AddField(
            model_name='fieldreview',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formassignment',
            name='degree_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_assignments', to='Colleges.degree'),
        ),
        migrations.AddField(
            model_name='formassignment',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_assignments', to='Colleges.academicprogram'),
        ),
        migrations.AddField(
            model_name='formassignment',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_assignments', to='Colleges.school'),
        ),
        migrations.AddField(
            model_name='formassignment',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_assignments', to='Colleges.university'),
        ),
        migrations.AddField(
            model_name='formassignment',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='Applicants.formdefinition'),
        ),
        migrations.AddField(
            model_name='dynamicworkflowstep',
            name='form',
            field=models.ForeignKey(blank=True, help_text='Linked form for form-type steps', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_steps', to='Applicants.formdefinition'),
        ),
        migrations.AddField(
            model_name='fieldresponse',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='Applicants.formfield'),
        ),
        migrations.AddField(
            model_name='fieldchoice',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='Applicants.formfield'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_responses', to='Applicants.application'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='Applicants.formdefinition'),
        ),
        migrations.AddField(
            model_name='fieldresponse',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_responses', to='Applicants.formresponse'),
        ),
        migrations.AddField(
            model_name='formsection',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='Applicants.formdefinition'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='Applicants.formsection'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='Applicants.formsection'),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_requests', to='Applicants.application'),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_requests_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_requests', to='Applicants.documentrequirement'),
        ),
        migrations.AddField(
            model_name='programrequirement',
            name='degree_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Colleges.degree'),
        ),
        migrations.AddField(
            model_name='programrequirement',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Colleges.academicprogram'),
        ),
        migrations.AddField(
            model_name='sectionassignment',
            name='degree_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_assignments', to='Colleges.degree'),
        ),
        migrations.AddField(
            model_name='sectionassignment',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_assignments', to='Colleges.academicprogram'),
        ),
        migrations.AddField(
            model_name='sectionassignment',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_assignments', to='Colleges.school'),
        ),
        migrations.AddField(
            model_name='sectionassignment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='Applicants.formsection'),
        ),
        migrations.AddField(
            model_name='sectionassignment',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_assignments', to='Colleges.university'),
        ),
        migrations.AddField(
            model_name='sectionreview',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_reviews', to='Applicants.applicationreviewassignment'),
        ),
        migrations.AddField(
            model_name='sectionreview',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='Applicants.stateprovince'),
        ),
        migrations.AddField(
            model_name='stepcondition',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='Applicants.dynamicworkflowstep'),
        ),
        migrations.AddField(
            model_name='universitydocumentrequirement',
            name='degree_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Colleges.degree'),
        ),
        migrations.AddField(
            model_name='universitydocumentrequirement',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Colleges.university'),
        ),
        migrations.AddField(
            model_name='universityessayrequirement',
            name='degree_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Colleges.degree'),
        ),
        migrations.AddField(
            model_name='universityessayrequirement',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Colleges.university'),
        ),
        migrations.AddField(
            model_name='validationrule',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='Applicants.formfield'),
        ),
        migrations.AddField(
            model_name='visibilityrule',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visibility_rules', to='Applicants.formfield'),
        ),
        migrations.AddField(
            model_name='visibilityrule',
            name='target_field',
            field=models.ForeignKey(help_text='Field whose value determines visibility', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Applicants.formfield'),
        ),
        migrations.AddField(
            model_name='workflowdefinition',
            name='degree_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='Colleges.degree'),
        ),
        migrations.AddField(
            model_name='workflowdefinition',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='Colleges.academicprogram'),
        ),
        migrations.AddField(
            model_name='workflowdefinition',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='Colleges.university'),
        ),
        migrations.AddField(
            model_name='dynamicworkflowstep',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='Applicants.workflowdefinition'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applicant', 'status'], name='application_applica_e9ee09_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['university', 'status'], name='application_univers_f33d82_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['degree_level', 'applicant_type'], name='application_degree__afd87c_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationchecklistitem',
            index=models.Index(fields=['application', 'code'], name='app_checkli_applica_d4df5f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='applicationchecklistitem',
            unique_together={('application', 'code')},
        ),
        migrations.AddIndex(
            model_name='documentrequirement',
            index=models.Index(fields=['university', 'degree_level', 'applicant_type'], name='dyn_documen_univers_390463_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentrequirement',
            unique_together={('code', 'university', 'degree_level')},
        ),
        migrations.AddIndex(
            model_name='essayprompt',
            index=models.Index(fields=['university', 'degree_level', 'applicant_type'], name='dyn_essay_p_univers_581813_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='applicationessay',
            unique_together={('application', 'essay_type')},
        ),
        migrations.AlterUniqueTogether(
            name='fieldreview',
            unique_together={('field_response', 'assignment')},
        ),
        migrations.AddIndex(
            model_name='formassignment',
            index=models.Index(fields=['university', 'degree_level', 'applicant_type'], name='dyn_form_as_univers_137256_idx'),
        ),
        migrations.AddIndex(
            model_name='formassignment',
            index=models.Index(fields=['form', 'is_active'], name='dyn_form_as_form_id_01bd5f_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldresponse',
            index=models.Index(fields=['response', 'field'], name='dyn_field_r_respons_a4b2d3_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldresponse',
            index=models.Index(fields=['field'], name='dyn_field_r_field_i_2fa52b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fieldresponse',
            unique_together={('response', 'field')},
        ),
        migrations.AlterUniqueTogether(
            name='formsection',
            unique_together={('form', 'code')},
        ),
        migrations.AddIndex(
            model_name='formresponse',
            index=models.Index(fields=['application', 'form'], name='dyn_form_re_applica_b1b971_idx'),
        ),
        migrations.AddIndex(
            model_name='formresponse',
            index=models.Index(fields=['application', 'section', 'repeat_index'], name='dyn_form_re_applica_596432_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='formresponse',
            unique_together={('application', 'section', 'repeat_index')},
        ),
        migrations.AlterUniqueTogether(
            name='formfield',
            unique_together={('section', 'code')},
        ),
        migrations.AddIndex(
            model_name='sectionassignment',
            index=models.Index(fields=['university', 'degree_level', 'applicant_type'], name='dyn_section_univers_b7627a_idx'),
        ),
        migrations.AddIndex(
            model_name='sectionassignment',
            index=models.Index(fields=['section', 'is_active'], name='dyn_section_section_f652f4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sectionreview',
            unique_together={('assignment', 'section_code')},
        ),
        migrations.AddIndex(
            model_name='workflowdefinition',
            index=models.Index(fields=['university', 'degree_level', 'applicant_type'], name='dyn_workflo_univers_75e3d9_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowdefinition',
            index=models.Index(fields=['code', 'is_active'], name='dyn_workflo_code_198af7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dynamicworkflowstep',
            unique_together={('workflow', 'code')},
        ),
    ]
