# Generated by Django 5.2.16 on 2026-09-16 05:09

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Faculty', '0001_initial'),
        ('bela_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_role', models.CharField(choices=[('FIRST', 'First Author'), ('CORRESPONDING', 'Corresponding Author'), ('CO_AUTHOR', 'Co Author')], max_length=30)),
                ('author_order', models.PositiveIntegerField()),
                ('is_full_crud', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['author_order'],
            },
        ),
        migrations.CreateModel(
            name='PublicationSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_name', models.CharField(blank=True, max_length=300)),
                ('conference_name', models.CharField(blank=True, max_length=300)),
                ('publisher', models.CharField(blank=True, max_length=300)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('manuscript_number', models.CharField(blank=True, max_length=100)),
                ('acceptance_date', models.DateField(blank=True, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, max_length=200)),
                ('publication_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('REVISION_REQUIRED', 'Revision Required'), ('RESUBMITTED', 'Resubmitted'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('PUBLISHED', 'Published'), ('WITHDRAWN', 'Withdrawn')], default='DRAFT', max_length=30)),
                ('is_full_crud', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentMilestoneAssignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('student_progress', models.PositiveIntegerField(default=0, help_text='Student completion percentage')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('working', 'Working'), ('submitted', 'Submitted'), ('completed', 'Completed')], default='assigned', max_length=20)),
                ('faculty_comment', models.TextField(blank=True, null=True)),
                ('is_full_crud', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProgressReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('progress_percentage', models.PositiveIntegerField()),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('revision', 'Revision Required'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('faculty_feedback', models.TextField(blank=True, null=True)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('is_full_crud', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentReportAttachment',
            fields=[
                ('attachment_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='research/report_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_full_crud', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentResearchApplication',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('application_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reference_number', models.CharField(blank=True, help_text='Auto-generated reference number', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20)),
                ('motivation', models.TextField()),
                ('skills_contribution', models.TextField()),
                ('prior_experience', models.TextField(blank=True, null=True)),
                ('time_commitment', models.CharField(choices=[('5-10', '5-10 hours/week'), ('10-15', '10-15 hours/week'), ('15-20', '15-20 hours/week'), ('20+', '20+ hours/week')], max_length=10)),
                ('availability', models.CharField(choices=[('semester', 'Full Semester'), ('summer', 'Summer Only'), ('winter', 'Winter Break'), ('year-round', 'Year Round')], max_length=20)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('resume', models.FileField(upload_to='applications/resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('statement_of_interest', models.FileField(upload_to='applications/statements/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('academic_transcript', models.FileField(upload_to='applications/transcripts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_full_crud', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'research_applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentResearchPublication',
            fields=[
                ('publication_id', models.AutoField(primary_key=True, serialize=False)),
                ('publication_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.TextField()),
                ('keywords', models.TextField(help_text='Comma separated keywords')),
                ('publication_type', models.CharField(choices=[('JOURNAL', 'Journal'), ('CONFERENCE', 'Conference'), ('BOOK_CHAPTER', 'Book Chapter'), ('TECHNICAL_REPORT', 'Technical Report')], max_length=30)),
                ('manuscript', models.FileField(blank=True, null=True, upload_to='publications/drafts/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under Internal Review'), ('COMMITTEE_REVIEW', 'Committee Review'), ('READY', 'Ready for Submission'), ('SUBMITTED', 'Submitted'), ('REVISION', 'Revision Required'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_full_crud', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('chair', 'Chairperson'), ('co-chair', 'Co-Chairperson'), ('secretary', 'Secretary'), ('member', 'Member')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_full_crud', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_committees', to='bela_admin.department')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_committees', to='Faculty.facultyprofile')),
                ('faculty_rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Faculty.facultyrank')),
            ],
            options={
                'ordering': ['-is_active', 'role', 'faculty__user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='ResearchOpportunity',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('research_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('research_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('estimated_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Estimated budget required for this research', max_digits=15)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=150)),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('application_open_date', models.DateField(blank=True, null=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('available_slots', models.PositiveIntegerField(default=1)),
                ('required_skills', models.TextField(blank=True, help_text='Comma separated skills')),
                ('reference_link', models.URLField(blank=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('project_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ONGOING', 'Ongoing'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ARCHIVED', 'Archived')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_full_crud', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='research_opportunities', to='bela_admin.department')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='research_opportunities', to='Faculty.facultyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchMilestone',
            fields=[
                ('milestone_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('deadline', models.DateField()),
                ('expected_percentage', models.PositiveIntegerField(default=0, help_text='Expected contribution percentage')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('delayed', 'Delayed')], default='not_started', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_full_crud', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_milestones', to='Faculty.facultyprofile')),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='Research.researchopportunity')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchFunding',
            fields=[
                ('funding_id', models.AutoField(primary_key=True, serialize=False)),
                ('funding_code', models.CharField(blank=True, editable=False, help_text='Non-sequential public-facing funding reference', max_length=30, unique=True)),
                ('funding_source', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('award_date', models.DateField()),
                ('sponsor', models.CharField(max_length=255)),
                ('is_full_crud', models.BooleanField(default=False)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundings', to='Research.researchopportunity')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchOpportunityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='research_opportunity_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_full_crud', models.BooleanField(default=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Research.researchopportunity')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchPresentation',
            fields=[
                ('presentation_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255)),
                ('presentation_date', models.DateField()),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='research/certificates/')),
                ('award', models.CharField(blank=True, max_length=255, null=True)),
                ('is_full_crud', models.BooleanField(default=False)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='Research.researchopportunity')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchPresentationDocument',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='research/presentation_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_full_crud', models.BooleanField(default=False)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Research.researchpresentation')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchProgress',
            fields=[
                ('progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('milestone', models.CharField(max_length=255)),
                ('progress_percentage', models.PositiveIntegerField()),
                ('report_file', models.FileField(blank=True, null=True, upload_to='research/progress_reports/')),
                ('submission_date', models.DateField()),
                ('is_full_crud', models.BooleanField(default=False)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='Research.researchopportunity')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200, unique=True)),
                ('is_full_crud', models.BooleanField(default=False)),
                ('research_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='research_teams', to='Research.researchopportunity')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADVISOR', 'Advisor'), ('CO_MENTOR', 'Co-Mentor'), ('STUDENT', 'Student')], max_length=20)),
                ('is_full_crud', models.BooleanField(default=False)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Faculty.facultyprofile')),
            ],
        ),
    ]
