# Generated by Django 5.2.16 on 2026-09-16 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Faculty', '0002_initial'),
        ('Research', '0001_initial'),
        ('Students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='researchteammember',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Students.studentprofile'),
        ),
        migrations.AddField(
            model_name='researchteammember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='Research.researchteam'),
        ),
        migrations.AddField(
            model_name='publicationauthor',
            name='team_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Research.researchteammember'),
        ),
        migrations.AddField(
            model_name='studentmilestoneassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Faculty.facultyprofile'),
        ),
        migrations.AddField(
            model_name='studentmilestoneassignment',
            name='milestone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='Research.researchmilestone'),
        ),
        migrations.AddField(
            model_name='studentmilestoneassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_milestones', to='Students.studentprofile'),
        ),
        migrations.AddField(
            model_name='studentprogressreport',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='Research.studentmilestoneassignment'),
        ),
        migrations.AddField(
            model_name='studentprogressreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Faculty.facultyprofile'),
        ),
        migrations.AddField(
            model_name='studentreportattachment',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='Research.studentprogressreport'),
        ),
        migrations.AddField(
            model_name='studentresearchapplication',
            name='research_opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='Research.researchopportunity'),
        ),
        migrations.AddField(
            model_name='studentresearchapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentresearchapplication',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_applications', to='Students.studentprofile'),
        ),
        migrations.AddField(
            model_name='studentresearchpublication',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Faculty.facultyprofile'),
        ),
        migrations.AddField(
            model_name='studentresearchpublication',
            name='research',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='Research.researchopportunity'),
        ),
        migrations.AddField(
            model_name='publicationsubmission',
            name='publication',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='Research.studentresearchpublication'),
        ),
        migrations.AddField(
            model_name='publicationauthor',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='Research.studentresearchpublication'),
        ),
        migrations.AddConstraint(
            model_name='researchcommittee',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('role', 'chair')), fields=('department',), name='one_active_chairperson_per_department'),
        ),
    ]
