# Generated by Django 5.2.16 on 2026-09-16 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship_code', models.CharField(max_length=30, unique=True)),
                ('scholarship_name', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('sponsor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('award_type', models.CharField(choices=[('FULL_TUITION', 'Full Tuition'), ('PARTIAL_TUITION', 'Partial Tuition'), ('FIXED_AMOUNT', 'Fixed Amount'), ('ROOM_AND_BOARD', 'Room and Board'), ('STIPEND', 'Stipend'), ('FELLOWSHIP', 'Fellowship'), ('ASSISTANTSHIP', 'Assistantship'), ('COMBINATION', 'Combination')], max_length=30)),
                ('award_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('number_of_awards', models.PositiveIntegerField(default=1)),
                ('renewable', models.BooleanField(default=False)),
                ('renewal_duration_years', models.PositiveIntegerField(default=0)),
                ('student_type', models.CharField(choices=[('DOMESTIC', 'Domestic'), ('INTERNATIONAL', 'International'), ('BOTH', 'Both')], default='BOTH', max_length=20)),
                ('degree_level', models.CharField(choices=[('UNDERGRADUATE', 'Undergraduate'), ('GRADUATE', 'Graduate'), ('PHD', 'PhD'), ('ALL', 'All')], default='ALL', max_length=20)),
                ('minimum_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('minimum_credits', models.PositiveIntegerField(blank=True, null=True)),
                ('financial_need_required', models.BooleanField(default=False)),
                ('first_generation_required', models.BooleanField(default=False)),
                ('leadership_required', models.BooleanField(default=False)),
                ('community_service_required', models.BooleanField(default=False)),
                ('essay_required', models.BooleanField(default=False)),
                ('recommendation_required', models.BooleanField(default=False)),
                ('additional_requirements', models.TextField(blank=True, null=True)),
                ('application_start_date', models.DateField()),
                ('application_deadline', models.DateField()),
                ('announcement_date', models.DateField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('DRAFT', 'Draft')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_full_crud', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='scholarship_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_full_crud', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('awarded_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('award_date', models.DateField()),
                ('renewal_status', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_full_crud', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_full_crud', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('is_full_crud', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(max_length=50, unique=True)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('personal_statement', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WAITLISTED', 'Waitlisted')], default='DRAFT', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_full_crud', models.BooleanField(default=False)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='Scholarships.scholarship')),
            ],
        ),
    ]
