# Generated by Django 5.2.16 on 2026-09-16 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Scholarships', '0001_initial'),
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.studentprofile'),
        ),
        migrations.AddField(
            model_name='scholarshipapplicationdocument',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Scholarships.scholarshipapplication'),
        ),
        migrations.AddField(
            model_name='scholarshipaward',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Scholarships.scholarshipapplication'),
        ),
        migrations.AddField(
            model_name='scholarshipaward',
            name='scholarship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='Scholarships.scholarship'),
        ),
        migrations.AddField(
            model_name='scholarshipaward',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.studentprofile'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='Scholarships.scholarshipcategory'),
        ),
        migrations.AddField(
            model_name='scholarshipdocument',
            name='scholarship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='Scholarships.scholarship'),
        ),
    ]
