# Generated by Django 5.2.16 on 2026-09-16 05:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Colleges', '0001_initial'),
        ('Medical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDesignationType',
            fields=[
                ('designation_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('designation_name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('is_full_crud', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CourseRequirementType',
            fields=[
                ('requirement_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_full_crud', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_type', models.CharField(choices=[('MEDICAL', 'Medical'), ('NORMAL', 'Normal')], default='NORMAL', max_length=50)),
                ('building_name', models.CharField(max_length=150)),
                ('building_code', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('building_image', models.ImageField(blank=True, null=True, upload_to='library/buildings/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_full_crud', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buildings', to='Medical.medicalcenter')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('course_code', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=255)),
                ('credits', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('office_location', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_full_crud', models.BooleanField(default=False)),
                ('academic_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='Colleges.academicprogram')),
                ('degree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='Colleges.degree')),
            ],
        ),
        migrations.CreateModel(
            name='CourseDesignation',
            fields=[
                ('designation_id', models.AutoField(primary_key=True, serialize=False)),
                ('designation_value', models.CharField(blank=True, max_length=255, null=True)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_full_crud', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='bela_admin.course')),
                ('designation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_designations', to='bela_admin.coursedesignationtype')),
            ],
        ),
        migrations.CreateModel(
            name='CourseLearningOutcome',
            fields=[
                ('outcome_id', models.AutoField(primary_key=True, serialize=False)),
                ('outcome', models.TextField()),
                ('audience', models.CharField(blank=True, default='Undergraduate', max_length=100, null=True)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_full_crud', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcomes', to='bela_admin.course')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='CourseRequirement',
            fields=[
                ('requirement_id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True, max_length=255, null=True)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_full_crud', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='bela_admin.course')),
                ('related_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_by', to='bela_admin.course')),
                ('requirement_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_requirements', to='bela_admin.courserequirementtype')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('department_code', models.CharField(max_length=20, unique=True)),
                ('department_name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('website', models.URLField(blank=True, null=True)),
                ('office_location', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('established_year', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_full_crud', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='Colleges.school')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='bela_admin.department'),
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_name', models.CharField(max_length=100)),
                ('floor_number', models.IntegerField()),
                ('is_full_crud', models.BooleanField(default=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='bela_admin.building')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=30)),
                ('room_name', models.CharField(max_length=150)),
                ('room_type', models.CharField(choices=[('CLASSROOM', 'Classroom'), ('LAB', 'Laboratory'), ('EXAM_HALL', 'Exam Hall'), ('SEMINAR', 'Seminar Hall')], max_length=30)),
                ('capacity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('MAINTENANCE', 'Maintenance'), ('BLOCKED', 'Blocked')], default='AVAILABLE', max_length=20)),
                ('has_projector', models.BooleanField(default=False)),
                ('has_computers', models.BooleanField(default=False)),
                ('has_ac', models.BooleanField(default=True)),
                ('is_full_crud', models.BooleanField(default=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='bela_admin.floor')),
            ],
        ),
        migrations.CreateModel(
            name='FacilityRoomAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_full_crud', models.BooleanField(default=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_allocations', to='Medical.facility')),
                ('medical_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_room_allocations', to='Medical.medicalcenter')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_allocations', to='bela_admin.room')),
            ],
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('offering_id', models.AutoField(primary_key=True, serialize=False)),
                ('term', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('Winter', 'Winter')], max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_full_crud', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='bela_admin.course')),
            ],
            options={
                'ordering': ['-year', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('course', 'term', 'year'), name='unique_course_offering')],
            },
        ),
        migrations.CreateModel(
            name='RoomPurposeAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('Patient Room', 'Patient Room'), ('Consultation Room', 'Consultation Room'), ('Examination Room', 'Examination Room'), ('Treatment Room', 'Treatment Room'), ('Procedure Room', 'Procedure Room'), ('Operating Room', 'Operating Room'), ('Pre-Operative Room', 'Pre-Operative Room'), ('Post-Operative Recovery Room', 'Post-Operative Recovery Room'), ('Emergency Room', 'Emergency Room'), ('Trauma Room', 'Trauma Room'), ('Isolation Room', 'Isolation Room'), ('Negative Pressure Room', 'Negative Pressure Room'), ('Infusion Room', 'Infusion Room'), ('Laboratory', 'Laboratory'), ('Pharmacy', 'Pharmacy'), ('Nursing Station', 'Nursing Station'), ("Doctor's Office", "Doctor's Office"), ('Staff Room', 'Staff Room'), ('Waiting Room', 'Waiting Room'), ('Patient Registration', 'Patient Registration'), ('Medical Records Room', 'Medical Records Room'), ('Clean Utility Room', 'Clean Utility Room'), ('Soiled Utility Room', 'Soiled Utility Room'), ('Sterilization Room', 'Sterilization Room'), ('Storage Room', 'Storage Room'), ('Housekeeping Room', 'Housekeeping Room'), ('Administrative Office', 'Administrative Office'), ('Conference Room', 'Conference Room'), ('Other', 'Other')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_full_crud', models.BooleanField(default=True)),
                ('medical_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_purpose_allocations', to='Medical.medicalcenter')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purpose_allocations', to='bela_admin.room')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('medical_center', 'room'), name='unique_room_purpose_per_hospital')],
            },
        ),
    ]
