"""
Django settings for wisconsin project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
""" Dominic Code Start's """
import os
# from decouple import config
""" Dominic Code End's """

# Rupa code start
from dotenv import load_dotenv

load_dotenv()

GROQ_API_KEY = os.environ.get("GROQ_API_KEY", "")
# Rupa code end

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
""" Dominic Update Code Start's """
SECRET_KEY = "django-insecure-+&+yyk^w%v@!hm2$jz^kbxc1-jm9wz2xv8&p)6h2$@3x6r6^70"
""" Dominic Update Code End's """

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

AUTH_USER_MODEL = 'Admin.User'

ALLOWED_HOSTS = ['*']

""" Dominic Code Start's """
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'
""" Dominic Code End's """

# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'channels',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Admin.Colleges.apps.CollegesConfig',
    'Admin.bela_admin',
    'Admin.Nebula',
    'Research.Elsa_research',
    'Admin','General','Staff','Faculty.apps.FacultyConfig','Students','Library.apps.LibraryConfig','Events','Medical','Research', 'PermissionAccess', 'Scholarships', 'Applicants',
    'django_countries',
    'notifications',
    # blaze code start
    'rest_framework',
    'corsheaders',
    # blaze code end
]

ASGI_APPLICATION = "wisconsin.asgi.application" 

CHANNEL_LAYERS = {
    "default": {"BACKEND": "channels.layers.InMemoryChannelLayer"},
}

# for  Production
# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels_redis.core.RedisChannelLayer",
#         "CONFIG": {"hosts": [("127.0.0.1", 6379)]},
#     },
# }

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    "Admin.middleware.AuditMiddleware",    
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Dominic Code Start's
    "PermissionAccess.middleware.PageAccessMiddleware",
    # Dominic Code End's
    # ____Eric code___
    # 'Staff.Eric.middleware.OfficeLoginMiddleware',
    # ____Eric code end____
    # Blaze code start
    'corsheaders.middleware.CorsMiddleware',  # ← Top-ல add
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #Blaze code end


]


ROOT_URLCONF = 'wisconsin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "Staff.context_processors.unread_notifications",
                "Research.Elsa_research.context_processors.research_team_member_status",
                "Medical.context_processors.vapid_public_key",
            ],
        },
    },
]

WSGI_APPLICATION = 'wisconsin.wsgi.application'
ASGI_APPLICATION = 'wisconsin.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

""" Dominic Code Start's """
PERMISSION_LOGIN_URL    = "/login/"
PERMISSION_REDIRECT_URL = "/"
PERMISSION_OPEN_PATHS = [
    "/login/", "/logout/", "/admin/", "/static/", "/media/", "/favicon.ico", "/permission/setup/",
    "/medical/staff/my-shifts/",
    "/medical/staff/push/",
    "/medical/staff/notifications/",
]

# Email configuration
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST_USER="deepak729729@gmail.com"
EMAIL_HOST_PASSWORD="yqdo czxl tkza frhn"

EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True



DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
""" Dominic Code End's """

#Eric code start
STRIPE_SECRET_KEY = "sk_test_51Tz8kaF5l9wFbbig5yiUMBS12gYQbWkZ3xiA203r4fsKyRiuxizZYfuwlp01wP3s9NEHCspsiJwP1IzURQNgFyKN00kZQQsiBh"
STRIPE_PUBLISHABLE_KEY = "pk_test_51Tz8kaF5l9wFbbigiYjiV9JYv5P6d7xI9zHmVvysthPTqM5PUHgqa0i0hnTdWiqBDmZEsvGUWdf0XHSaTYpL51Pk0074oQuiAr"
STRIPE_WEBHOOK_SECRET = "whsec_077086f5bed2a2c907ac79b75961afd2d950d00cbde1175669d703b0435d4048"
#Eric code end

""" Dominic Code Start's """
VAPID_PUBLIC_KEY = 'BASCihPh2EvEdkWHHtDpp-GcmNdrerwqvEDMsiYgGkV8tjU5SRDTfDiGoc4SMwVpLda3TI2gj5NpmV6GnyqJnCM'
VAPID_PRIVATE_KEY = """
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg2JUJ206UlAiQ31mm
PD0nqjA4OohT859FjZsXBlpVGpWhRANCAAQEgooT4dhLxHZFhx7Q6afhnJjXa3q8
KrxAzLImIBpFfLY1OUkQ03w4hqHOEjMFaS3Wt0yNoI+TaZlehp8qiZwj
"""
VAPID_CLAIMS = {"sub": "mailto:deepak729729@gmail.com"}
""" Dominic Code End's """


# Blaze code
CORS_ALLOW_ALL_ORIGINS = True
