# Generated by Django 5.2.16 on 2026-09-16 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Faculty', '0001_initial'),
        ('Medical', '0001_initial'),
        ('PermissionAccess', '0001_initial'),
        ('Staff', '0001_initial'),
        ('bela_admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_facilities', to='bela_admin.room'),
        ),
        migrations.AddField(
            model_name='facilitymaintenance',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_history', to='Medical.facility'),
        ),
        migrations.AddField(
            model_name='healthcampregistry',
            name='health_camp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='Medical.healthcamp'),
        ),
        migrations.AddField(
            model_name='injuryrecord',
            name='medical_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injury_records', to='Medical.athletemedicalprofile'),
        ),
        migrations.AddField(
            model_name='medicalcenter',
            name='director_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_centers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalcenter',
            name='hospital_building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_centers', to='bela_admin.building'),
        ),
        migrations.AddField(
            model_name='hospitalstatistics',
            name='medical_center',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='Medical.medicalcenter'),
        ),
        migrations.AddField(
            model_name='hospitalgallery',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='Medical.medicalcenter'),
        ),
        migrations.AddField(
            model_name='facilitymaintenance',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='Medical.medicalcenter'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='Medical.medicalcenter'),
        ),
        migrations.AddField(
            model_name='medicaldepartment',
            name='hospitals',
            field=models.ManyToManyField(blank=True, help_text='Hospitals where this department is directly available. Optional — leave empty and the department will still show up for a hospital once a staff member is assigned there (old behavior, unaffected).', related_name='departments', to='Medical.medicalcenter'),
        ),
        migrations.AddField(
            model_name='medicalcenter',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Medical.medicaldepartment'),
        ),
        migrations.AddField(
            model_name='healthcamp',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_camps', to='Medical.medicaldepartment'),
        ),
        migrations.AddField(
            model_name='medicalservice',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='Medical.medicaldepartment'),
        ),
        migrations.AddField(
            model_name='medicalstaffprofile',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='Medical.medicaldepartment'),
        ),
        migrations.AddField(
            model_name='medicalstaffprofile',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medical_staff', to='Medical.medicalcenter'),
        ),
        migrations.AddField(
            model_name='medicalstaffprofile',
            name='reporting_to',
            field=models.ForeignKey(blank=True, help_text='Senior staff this person reports to. Left blank for senior doctors — they report directly to the hospital director instead.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='Medical.medicalstaffprofile'),
        ),
        migrations.AddField(
            model_name='medicalstaffprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalstaffprofile',
            name='work_facilities',
            field=models.ManyToManyField(blank=True, help_text='Hospital facilities this staff member primarily works in.', related_name='assigned_staff', to='Medical.facility'),
        ),
        migrations.AddField(
            model_name='medicalstaffleave',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_medical_staff_leaves', to='Medical.medicalstaffprofile'),
        ),
        migrations.AddField(
            model_name='medicalstaffleave',
            name='medical_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='Medical.medicalstaffprofile'),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to='Medical.medicalstaffprofile'),
        ),
        migrations.AddField(
            model_name='laboratorytest',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_tests', to='Medical.medicalstaffprofile'),
        ),
        migrations.AddField(
            model_name='laboratorytest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_tests', to='Medical.medicalstaffprofile'),
        ),
        migrations.AddField(
            model_name='injuryrecord',
            name='treated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Medical.medicalstaffprofile'),
        ),
        migrations.AddField(
            model_name='healthcamp',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organized_health_camps', to='Medical.medicalstaffprofile'),
        ),
        migrations.AddField(
            model_name='dailynote',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_notes', to='Medical.medicalstaffprofile'),
        ),
        migrations.AddField(
            model_name='athletemedicalprofile',
            name='physiotherapist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_athletes_as_physio', to='Medical.medicalstaffprofile'),
        ),
        migrations.AddField(
            model_name='athletemedicalprofile',
            name='team_physician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_athletes_as_doctor', to='Medical.medicalstaffprofile'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='medical_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='Medical.medicalstaffprofile'),
        ),
        migrations.AddField(
            model_name='medicalstaffrole',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='medical_staff_roles', to='PermissionAccess.permission'),
        ),
        migrations.AddField(
            model_name='medicalstaffprofile',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_members', to='Medical.medicalstaffrole'),
        ),
        migrations.AddField(
            model_name='medicalvisit',
            name='athlete_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_visits', to='Medical.athletemedicalprofile'),
        ),
        migrations.AddField(
            model_name='medicalvisit',
            name='attending_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_visits', to='Medical.medicalstaffprofile'),
        ),
        migrations.AddField(
            model_name='medicalvisit',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_visits', to='Medical.medicaldepartment'),
        ),
        migrations.AddField(
            model_name='medicalvisit',
            name='injury_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_visits', to='Medical.injuryrecord'),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='medical_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='Medical.medicalvisit'),
        ),
        migrations.AddField(
            model_name='laboratorytest',
            name='medical_visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratory_tests', to='Medical.medicalvisit'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='admin',
            field=models.OneToOneField(blank=True, limit_choices_to={'is_admin': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_admin_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='faculty',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_faculty_profile', to='Faculty.facultyprofile'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='staff',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_staff_profile', to='Staff.staffprofile'),
        ),
    ]
