# Generated by Django 5.2.16 on 2026-09-16 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0002_initial'),
        ('Faculty', '0002_initial'),
        ('Medical', '0002_initial'),
        ('Staff', '0001_initial'),
        ('Students', '0001_initial'),
        ('bela_admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_student_profile', to='Students.studentprofile'),
        ),
        migrations.AddField(
            model_name='medicalvisit',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_visits', to='Medical.patientprofile'),
        ),
        migrations.AddField(
            model_name='laboratorytest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratory_tests', to='Medical.patientprofile'),
        ),
        migrations.AddField(
            model_name='athletemedicalprofile',
            name='patient_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='athlete_profile', to='Medical.patientprofile'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='Medical.patientprofile'),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='admission_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_admissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='admitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admitted_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_registrations', to='Medical.appointment'),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='assigned_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admitted_registrations', to='bela_admin.room'),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient_registrations', to='Medical.medicalcenter'),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='medical_visit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration', to='Medical.medicalvisit'),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='Medical.patientprofile'),
        ),
        migrations.AddField(
            model_name='patientregistry',
            name='athlete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_records', to='Admin.athletic'),
        ),
        migrations.AddField(
            model_name='patientregistry',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_records', to='Faculty.facultyprofile'),
        ),
        migrations.AddField(
            model_name='patientregistry',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_records', to='Staff.staffprofile'),
        ),
        migrations.AddField(
            model_name='patientregistry',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_records', to='Students.studentprofile'),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_documents', to='Medical.patientregistry'),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roomcheckupnote',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_checkup_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roomcheckupnote',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkup_notes', to='Medical.patientregistration'),
        ),
        migrations.AddField(
            model_name='shift',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shift',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='Medical.medicaldepartment'),
        ),
        migrations.AddField(
            model_name='shift',
            name='hospital',
            field=models.ForeignKey(blank=True, help_text='Which hospital this shift belongs to. Needed since the same department name can exist across multiplhospitals.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='Medical.medicalcenter'),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_registrations', to='Medical.shift'),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_shift_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='medical_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='Medical.medicalstaffprofile'),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Which room this staff member is covering for this shift assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_assignments', to='bela_admin.room'),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='Medical.shift'),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='shift_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_registrations', to='Medical.shiftassignment'),
        ),
        migrations.AlterUniqueTogether(
            name='dailynote',
            unique_together={('staff', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='shiftassignment',
            unique_together={('shift', 'medical_staff')},
        ),
        migrations.AddConstraint(
            model_name='patientregistration',
            constraint=models.UniqueConstraint(fields=('shift_assignment', 'registration_date', 'token_number'), name='unique_daily_assignment_token'),
        ),
    ]
