# Generated by Django 5.2.16 on 2026-09-16 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0002_initial'),
        ('Faculty', '0001_initial'),
        ('Students', '0001_initial'),
        ('bela_admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advisorstudentmessage',
            name='phd_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisor_student_messages', to='Students.phdstudent'),
        ),
        migrations.AddField(
            model_name='advisorstudentmessageattachment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='Faculty.advisorstudentmessage'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='Students.studentprofile'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='bela_admin.course'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='Students.schedule'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='Students.coursesection'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendance_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='Faculty.attendancesession'),
        ),
        migrations.AddField(
            model_name='coursegrade',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bela_admin.course'),
        ),
        migrations.AddField(
            model_name='coursegrade',
            name='grade_scale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.gradescale'),
        ),
        migrations.AddField(
            model_name='coursegrade',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.semester'),
        ),
        migrations.AddField(
            model_name='coursegrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.studentprofile'),
        ),
        migrations.AddField(
            model_name='coursework',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseworks', to='Students.phd'),
        ),
        migrations.AddField(
            model_name='courseworkevaluation',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='Faculty.courseworksubmission'),
        ),
        migrations.AddField(
            model_name='dissertationadvisoradvice',
            name='dissertation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advisor_advice', to='Students.dissertation'),
        ),
        migrations.AddField(
            model_name='dissertationadvisorfeedback',
            name='dissertation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advisor_feedback', to='Students.dissertation'),
        ),
        migrations.AddField(
            model_name='dissertationapproval',
            name='dissertation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_approval', to='Students.dissertation'),
        ),
        migrations.AddField(
            model_name='dissertationchairreplyfeedback',
            name='advisor_feedback',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chair_reply_feedback', to='Faculty.dissertationadvisorfeedback'),
        ),
        migrations.AddField(
            model_name='dissertationchairreplyfeedback',
            name='dissertation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chair_reply_feedback', to='Students.dissertation'),
        ),
        migrations.AddField(
            model_name='dissertationevaluation',
            name='committee_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dissertation_evaluations', to='Students.committeemember'),
        ),
        migrations.AddField(
            model_name='dissertationevaluation',
            name='dissertation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_evaluations', to='Students.dissertation'),
        ),
        migrations.AddField(
            model_name='facultycoursework',
            name='coursework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faculty_courseworks', to='Faculty.coursework'),
        ),
        migrations.AddField(
            model_name='facultycoursework',
            name='phd_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_courseworks', to='Students.phdstudent'),
        ),
        migrations.AddField(
            model_name='facultycoursework',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_courseworks', to='Students.phd'),
        ),
        migrations.AddField(
            model_name='courseworksubmission',
            name='coursework',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='Faculty.facultycoursework'),
        ),
        migrations.AddField(
            model_name='facultyleavebalance',
            name='faculty',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculties', to='bela_admin.department'),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facultyofficehours',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_hours', to='Faculty.facultyprofile'),
        ),
        migrations.AddField(
            model_name='facultygrant',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='Faculty.facultyprofile'),
        ),
        migrations.AddField(
            model_name='facultyevaluation',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='Faculty.facultyprofile'),
        ),
        migrations.AddField(
            model_name='facultyeducation',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_records', to='Faculty.facultyprofile'),
        ),
        migrations.AddField(
            model_name='facultydocument',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Faculty.facultyprofile'),
        ),
        migrations.AddField(
            model_name='facultycourseassignment',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='Faculty.facultyprofile'),
        ),
        migrations.AddField(
            model_name='facultycommittee',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_memberships', to='Faculty.facultyprofile'),
        ),
        migrations.AddField(
            model_name='facultyappointment',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='Faculty.facultyprofile'),
        ),
        migrations.AddField(
            model_name='dissertationchairreplyfeedback',
            name='chair_faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chair_reply_feedbacks', to='Faculty.facultyprofile'),
        ),
        migrations.AddField(
            model_name='dissertationapproval',
            name='chair_faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dissertation_approvals', to='Faculty.facultyprofile'),
        ),
        migrations.AddField(
            model_name='dissertationadvisorfeedback',
            name='advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisor_feedbacks', to='Faculty.facultyprofile'),
        ),
        migrations.AddField(
            model_name='dissertationadvisoradvice',
            name='advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dissertation_advices', to='Faculty.facultyprofile'),
        ),
        migrations.AddField(
            model_name='courseworkevaluation',
            name='evaluated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coursework_evaluations', to='Faculty.facultyprofile'),
        ),
        migrations.AddField(
            model_name='coursework',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_courseworks', to='Faculty.facultyprofile'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='Faculty.facultyprofile'),
        ),
        migrations.AddField(
            model_name='advisorstudentmessage',
            name='advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisor_student_messages', to='Faculty.facultyprofile'),
        ),
        migrations.AddField(
            model_name='advisorresearchadvice',
            name='advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='research_milestone_advices', to='Faculty.facultyprofile'),
        ),
        migrations.AddField(
            model_name='facultypublication',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='Faculty.facultyprofile'),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='faculty_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_members', to='Faculty.facultyrank'),
        ),
        migrations.AddField(
            model_name='facultyresearch',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_projects', to='Faculty.facultyprofile'),
        ),
        migrations.AddField(
            model_name='finaldissertationadvisorevaluation',
            name='advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_dissertation_advisor_evaluations', to='Faculty.facultyprofile'),
        ),
        migrations.AddField(
            model_name='finaldissertationadvisorevaluation',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisor_evaluations', to='Students.finaldissertationsubmission'),
        ),
        migrations.AddField(
            model_name='finaldissertationcommitteeevaluation',
            name='committee_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_dissertation_evaluations', to='Students.committeemember'),
        ),
        migrations.AddField(
            model_name='finaldissertationcommitteeevaluation',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_evaluations', to='Students.finaldissertationsubmission'),
        ),
        migrations.AddField(
            model_name='gradechangerequest',
            name='current_grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_grade_requests', to='Admin.gradescale'),
        ),
        migrations.AddField(
            model_name='gradechangerequest',
            name='requested_grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_grade_requests', to='Admin.gradescale'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Faculty.leavetype'),
        ),
        migrations.AddField(
            model_name='preliminaryexamevaluation',
            name='examination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='Students.preliminaryexamination'),
        ),
        migrations.AddField(
            model_name='preliminaryexamevaluation',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preliminary_exam_evaluations', to='Faculty.facultyprofile'),
        ),
        migrations.AddField(
            model_name='researchmilestone',
            name='chair_faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_research_milestones', to='Faculty.facultyprofile'),
        ),
        migrations.AddField(
            model_name='researchmilestone',
            name='phd_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_milestones', to='Students.phdstudent'),
        ),
        migrations.AddField(
            model_name='researchmilestoneevaluation',
            name='evaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='research_milestone_evaluations', to='Faculty.facultyprofile'),
        ),
        migrations.AddField(
            model_name='researchmilestonesubmission',
            name='milestone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='Faculty.researchmilestone'),
        ),
        migrations.AddField(
            model_name='researchmilestoneevaluation',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='Faculty.researchmilestonesubmission'),
        ),
        migrations.AddField(
            model_name='advisorresearchadvice',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisor_advices', to='Faculty.researchmilestonesubmission'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('attendance_session', 'student')},
        ),
        migrations.AddConstraint(
            model_name='dissertationevaluation',
            constraint=models.UniqueConstraint(fields=('dissertation', 'committee_member'), name='unique_dissertation_committee_evaluation'),
        ),
        migrations.AddConstraint(
            model_name='facultycoursework',
            constraint=models.UniqueConstraint(fields=('phd_student', 'coursework'), name='unique_student_coursework'),
        ),
        migrations.AddConstraint(
            model_name='dissertationchairreplyfeedback',
            constraint=models.UniqueConstraint(fields=('dissertation', 'chair_faculty'), name='unique_dissertation_chair_reply_feedback'),
        ),
        migrations.AddConstraint(
            model_name='dissertationadvisorfeedback',
            constraint=models.UniqueConstraint(fields=('dissertation', 'advisor'), name='unique_dissertation_advisor_feedback'),
        ),
        migrations.AddConstraint(
            model_name='dissertationadvisoradvice',
            constraint=models.UniqueConstraint(fields=('dissertation', 'advisor'), name='unique_dissertation_advisor_advice'),
        ),
        migrations.AddConstraint(
            model_name='coursework',
            constraint=models.UniqueConstraint(fields=('program', 'coursework_name'), name='unique_program_coursework_name'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancesession',
            unique_together={('section', 'schedule', 'attendance_date')},
        ),
        migrations.AddConstraint(
            model_name='finaldissertationadvisorevaluation',
            constraint=models.UniqueConstraint(fields=('submission', 'advisor', 'submission_number'), name='unique_final_dissertation_advisor_evaluation'),
        ),
        migrations.AddConstraint(
            model_name='finaldissertationcommitteeevaluation',
            constraint=models.UniqueConstraint(fields=('submission', 'committee_member', 'submission_number'), name='unique_final_dissertation_committee_evaluation'),
        ),
        migrations.AddConstraint(
            model_name='preliminaryexamevaluation',
            constraint=models.UniqueConstraint(fields=('examination', 'faculty'), name='unique_preliminary_exam_faculty_evaluation'),
        ),
        migrations.AddConstraint(
            model_name='researchmilestone',
            constraint=models.UniqueConstraint(fields=('phd_student', 'sequence_number'), name='unique_student_research_milestone_sequence'),
        ),
        migrations.AddConstraint(
            model_name='researchmilestonesubmission',
            constraint=models.UniqueConstraint(fields=('milestone', 'submission_number'), name='unique_research_milestone_submission_number'),
        ),
        migrations.AddConstraint(
            model_name='researchmilestoneevaluation',
            constraint=models.UniqueConstraint(fields=('submission', 'evaluator'), name='unique_research_submission_evaluator'),
        ),
        migrations.AddConstraint(
            model_name='advisorresearchadvice',
            constraint=models.UniqueConstraint(fields=('submission', 'advisor'), name='unique_research_submission_advisor_advice'),
        ),
    ]
